name: m3u_xmltv
description: A fast parser for M3U playlists and XMLTV EPG files with built-in channel matching.
version: 0.1.0
repository: https://github.com/M26Tash/m3u_xmltv

environment:
  sdk: ^3.12.2

dependencies:
  equatable: ^2.1.0
  xml: ^7.0.1

dev_dependencies:
  http: ^1.6.0
  lints: ^6.0.0
  test: ^1.25.6